# Ch2. 사이킷런으로 시작하는 머신러닝

## sklearn

In [1]:
!pip install scikit-learn

In [2]:
import sklearn

In [3]:
print(sklearn.__version__)

1.0.2


## 붓꽃 품종 예측하기

### import

In [4]:
from sklearn.datasets import load_iris # 붓꽃 데이터 세트 생성
from sklearn.tree import DecisionTreeClassifier # 의사 결정 트리
from sklearn.model_selection import train_test_split # 데이터 세트를 학습 데이터와 테스트 데이터로 분리

In [5]:
import pandas as pd

### preview

In [6]:
iris = load_iris()

In [7]:
iris_data = iris.data
iris_label = iris.target

In [8]:
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
iris_df['lable'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   lable  
0      0  
1      0  
2      0  
3      0  
4      0

### train_test_split()

In [12]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size=0.2, random_state=11)

- `X_train` : 학습용 피쳐 데이터 세트

- `X_test` : 테스트용 피쳐 데이터 세트

- `y_train` : 학습용 레이블 데이터 세트

- `y_test` : 테스트용 레이블 데이터 세트

- `iris_data` : 피쳐 데이터 세트

- `iris_data` : 레이브 데이터 세트

- `test_size` : 전체 데이터 세트 중 테스트 데이터 세트의 비율

- `random_state` : seed와 같은 의미로 교재 재현성 확보를 위한 옵션

In [13]:
X_test.size / iris_data.size

0.2

In [14]:
y_test.size / iris_label.size

0.2

### DecisionTreeClassifier 객체 생성

In [15]:
dt_clf = DecisionTreeClassifier(random_state=11)

### 학습 수행

In [16]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [17]:
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

### 학습 정확도 확인

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test, pred)

0.9333333333333333

In [20]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

### 정리

`1. 데이터 세트 분리`: 데이터를 학습 데이터와 테스트 데이터로 분리합니다.

`2. 모델 학습`: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킵니다.

`3. 예측 수행`: 학습된 ML 모델을 이용해 테스트 데이터의 분류(즉, 붓꽃 종류)를 예측합니다.

`4. 평가`: 에측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가합니다.

## 사이킷런의 기반 프레임워크 익히기

In [21]:
from sklearn.datasets import load_iris

In [22]:
iris_data = load_iris()

In [23]:
type(iris_data)

sklearn.utils.Bunch

- Bunch 클래스는 파이썬 딕셔너리 자료형과 유사하다.

In [24]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

## Model Selection 모듈 소개

In [25]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [26]:
iris = load_iris()

In [27]:
dt_clf = DecisionTreeClassifier()

In [28]:
train_data = iris.data
train_label = iris.target

In [29]:
dt_clf.fit(train_data, train_label)

DecisionTreeClassifier()

In [30]:
# 학습 데이터세트로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도 : ', accuracy_score(train_label, pred))

예측 정확도 :  1.0


- 예측 정확도가 100%인 것은 이미 학습한 학습 데이터 세트를 기반으로 예측했기 때문이다.

- `train_test_split()`를 이용해 학습 및 테스트 데이터 세트로 분리해야 한다.

In [31]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [32]:
dt_clt = DecisionTreeClassifier()
iris_data = load_iris()

In [33]:
X_train, X_test, y_train, y_test = train_test_split(iris_data['data'], iris_data['target'],
                                                    test_size = 0.3, random_state=121)

In [34]:
dt_clt.fit(X_train, y_train)

DecisionTreeClassifier()

In [35]:
pred = dt_clt.predict(X_test)
print('예측 정확도 : ', accuracy_score(y_test, pred))

예측 정확도 :  0.9555555555555556


## K 폴드 교차 검증

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [37]:
iris = load_iris()

In [38]:
features = iris['data']

In [39]:
label = iris['target']

In [40]:
dt_clf = DecisionTreeClassifier(random_state=156)

In [41]:
# 5개의 폴드세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.

kfold = KFold(n_splits = 5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [42]:
n_iter = 0

# KFold 객체의 split()를  호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 변환

for train_index, test_index in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter = n_iter + 1
    
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'. format(n_iter, test_index))
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산

print('\n ## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 평균 검증 정확도:  0.9


## -- 

## cross_val_score()

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

In [44]:
import numpy as np 

In [45]:
iris_data = load_iris()

In [46]:
dt_clf = DecisionTreeClassifier(random_state=156)

In [47]:
data = iris_data['data']
label = iris_data['target']

In [48]:
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)

In [49]:
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


## GridSearchCV

In [50]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [51]:
iris_data = load_iris()

In [52]:
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size = 0.2, random_state=121)

In [53]:
dtree = DecisionTreeClassifier()

In [59]:
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [60]:
import pandas as pd

In [61]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

In [62]:
grid_dtree

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [63]:
grid_dtree.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [67]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 
          'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

## One-Hot Encoding

In [77]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [82]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [83]:
# 먼저 숫자 값으로 변환을 위해 LabelEncodr로 변환합니다.
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(items)

In [84]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [85]:
# 2차원 데이터로 변환합니다.

labels = labels.reshape(-1, 1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [86]:
# 원-핫 인코딩을 적용합니다.

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [88]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### get_dummies()

In [89]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [90]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0