In [2]:
import numpy as np

In [6]:
array1 = np.array([1,2,3])

In [7]:
print('array1 type:', type(array1))

array1 type: <class 'numpy.ndarray'>


## ndarray의 차원과 크기를 변경하는 reshape()

In [14]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.reshape(array1, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### -1값을 인자로 적용

- 인자 하나를 -1로하면 나머지 인자는 알아서 결정해준다.

In [19]:
array1.reshape(2, - 1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
array1 = np.arange(8)

In [26]:
array3d = array1.reshape([2,2,2]) # 3차원으로

In [22]:
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
array5 = array3d.reshape(-1,1) # 2차원으로

In [25]:
array5

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [3]:
array1 = np.arange(start=1 , stop = 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2 = np.arange(1, 10).reshape(3,3)

In [5]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [8]:
org_array = np.array([3,1,9,5])
org_array

array([3, 1, 9, 5])

In [9]:
np.sort(org_array)

array([1, 3, 5, 9])

In [13]:
?org_array.sort()

Object `org_array.sort()` not found.


In [11]:
org_array

array([1, 3, 5, 9])

In [24]:
org_array

array([1, 3, 5, 9])

In [25]:
sort_array1_desc = np.sort(org_array)[::-1]

In [26]:
sort_array1_desc

array([9, 5, 3, 1])

In [27]:
array2d = np.array([[8, 12], [7, 1]])

In [28]:
array2d

array([[ 8, 12],
       [ 7,  1]])

In [32]:
np.sort(array2d)

array([[ 8, 12],
       [ 1,  7]])

In [34]:
np.sort(array2d, axis =0 )

array([[ 7,  1],
       [ 8, 12]])

In [35]:
np.sort(array2d, axis =1 )

array([[ 8, 12],
       [ 1,  7]])

In [39]:
array1 = np.array([3,1,9,5])
np.argsort(array1)

array([1, 0, 3, 2], dtype=int64)

In [40]:
array1[np.argsort(array1)]

array([1, 3, 5, 9])