In [3]:
import numpy as np

In [6]:
array1 = np.array([1,2,3])

In [7]:
print('array1 type:', type(array1))

array1 type: <class 'numpy.ndarray'>


## ndarray의 차원과 크기를 변경하는 reshape()

In [14]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.reshape(array1, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### -1값을 인자로 적용

- 인자 하나를 -1로하면 나머지 인자는 알아서 결정해준다.

In [19]:
array1.reshape(2, - 1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
array1 = np.arange(8)

In [26]:
array3d = array1.reshape([2,2,2]) # 3차원으로

In [22]:
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
array5 = array3d.reshape(-1,1) # 2차원으로

In [25]:
array5

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])